# Generated by Django 5.1.6 on 2025-02-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
